/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ZGDB_SERVICE_H
#define ZGDB_SERVICE_H

#include <thrift/c_glib/processor/thrift_dispatch_processor.h>

#include "structs_types.h"

/* zgdbService service interface */
typedef struct _zgdbServiceIf zgdbServiceIf;  /* dummy object */

struct _zgdbServiceIfInterface
{
  GTypeInterface parent;

  gboolean (*execute) (zgdbServiceIf *iface, gchar ** _return, const astNode_t * tree, GError **error);
};
typedef struct _zgdbServiceIfInterface zgdbServiceIfInterface;

GType zgdb_service_if_get_type (void);
#define TYPE_ZGDB_SERVICE_IF (zgdb_service_if_get_type())
#define ZGDB_SERVICE_IF(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ZGDB_SERVICE_IF, zgdbServiceIf))
#define IS_ZGDB_SERVICE_IF(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ZGDB_SERVICE_IF))
#define ZGDB_SERVICE_IF_GET_INTERFACE(inst) (G_TYPE_INSTANCE_GET_INTERFACE ((inst), TYPE_ZGDB_SERVICE_IF, zgdbServiceIfInterface))

gboolean zgdb_service_if_execute (zgdbServiceIf *iface, gchar ** _return, const astNode_t * tree, GError **error);

/* zgdbService service client */
struct _zgdbServiceClient
{
  GObject parent;

  ThriftProtocol *input_protocol;
  ThriftProtocol *output_protocol;
};
typedef struct _zgdbServiceClient zgdbServiceClient;

struct _zgdbServiceClientClass
{
  GObjectClass parent;
};
typedef struct _zgdbServiceClientClass zgdbServiceClientClass;

GType zgdb_service_client_get_type (void);
#define TYPE_ZGDB_SERVICE_CLIENT (zgdb_service_client_get_type())
#define ZGDB_SERVICE_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ZGDB_SERVICE_CLIENT, zgdbServiceClient))
#define ZGDB_SERVICE_CLIENT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), TYPE_ZGDB_SERVICE_CLIENT, zgdbServiceClientClass))
#define ZGDB_SERVICE_IS_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ZGDB_SERVICE_CLIENT))
#define ZGDB_SERVICE_IS_CLIENT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_ZGDB_SERVICE_CLIENT))
#define ZGDB_SERVICE_CLIENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ZGDB_SERVICE_CLIENT, zgdbServiceClientClass))

gboolean zgdb_service_client_execute (zgdbServiceIf * iface, gchar ** _return, const astNode_t * tree, GError ** error);
gboolean zgdb_service_client_send_execute (zgdbServiceIf * iface, const astNode_t * tree, GError ** error);
gboolean zgdb_service_client_recv_execute (zgdbServiceIf * iface, gchar ** _return, GError ** error);
void zgdb_service_client_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec);
void zgdb_service_client_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec);

/* zgdbService handler (abstract base class) */
struct _zgdbServiceHandler
{
  GObject parent;
};
typedef struct _zgdbServiceHandler zgdbServiceHandler;

struct _zgdbServiceHandlerClass
{
  GObjectClass parent;

  gboolean (*execute) (zgdbServiceIf *iface, gchar ** _return, const astNode_t * tree, GError **error);
};
typedef struct _zgdbServiceHandlerClass zgdbServiceHandlerClass;

GType zgdb_service_handler_get_type (void);
#define TYPE_ZGDB_SERVICE_HANDLER (zgdb_service_handler_get_type())
#define ZGDB_SERVICE_HANDLER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ZGDB_SERVICE_HANDLER, zgdbServiceHandler))
#define IS_ZGDB_SERVICE_HANDLER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ZGDB_SERVICE_HANDLER))
#define ZGDB_SERVICE_HANDLER_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), TYPE_ZGDB_SERVICE_HANDLER, zgdbServiceHandlerClass))
#define IS_ZGDB_SERVICE_HANDLER_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_ZGDB_SERVICE_HANDLER))
#define ZGDB_SERVICE_HANDLER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ZGDB_SERVICE_HANDLER, zgdbServiceHandlerClass))

gboolean zgdb_service_handler_execute (zgdbServiceIf *iface, gchar ** _return, const astNode_t * tree, GError **error);

/* zgdbService processor */
struct _zgdbServiceProcessor
{
  ThriftDispatchProcessor parent;

  /* protected */
  zgdbServiceHandler *handler;
  GHashTable *process_map;
};
typedef struct _zgdbServiceProcessor zgdbServiceProcessor;

struct _zgdbServiceProcessorClass
{
  ThriftDispatchProcessorClass parent;

  /* protected */
  gboolean (*dispatch_call) (ThriftDispatchProcessor *processor,
                             ThriftProtocol *in,
                             ThriftProtocol *out,
                             gchar *fname,
                             gint32 seqid,
                             GError **error);
};
typedef struct _zgdbServiceProcessorClass zgdbServiceProcessorClass;

GType zgdb_service_processor_get_type (void);
#define TYPE_ZGDB_SERVICE_PROCESSOR (zgdb_service_processor_get_type())
#define ZGDB_SERVICE_PROCESSOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ZGDB_SERVICE_PROCESSOR, zgdbServiceProcessor))
#define IS_ZGDB_SERVICE_PROCESSOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ZGDB_SERVICE_PROCESSOR))
#define ZGDB_SERVICE_PROCESSOR_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), TYPE_ZGDB_SERVICE_PROCESSOR, zgdbServiceProcessorClass))
#define IS_ZGDB_SERVICE_PROCESSOR_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_ZGDB_SERVICE_PROCESSOR))
#define ZGDB_SERVICE_PROCESSOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ZGDB_SERVICE_PROCESSOR, zgdbServiceProcessorClass))

#endif /* ZGDB_SERVICE_H */
